### ISSUE TITLE
Currently, there's an issue when using `wire:model`

### ISSUE THREAD

**Issue by marcreichel** [marcreichel/alpine-autosize#1]
When using `x-autosize` together with `wire:model` the size of the `textarea` is not calculated correctly.

**Comment by nsouto** [comment]
Before finding your plugin, I've been having this exact problem with Livewire and AutoResize of textareas.

Still unsure how to resolve it, if I find anything I'll let you know, hopefully, a nice solution can be found.

Thanks for your work on this ;)

**Comment by marcreichel** [comment]
@nsouto Thank you, I would appreciate it 👍🏼🙂

**Comment by vantruong3289** [comment]
I see it still error

**Comment by marcreichel** [comment]
@vantruong3289 Could you describe what your problem is exactly? What version of `alpine-autosize` are you using?

**Comment by vantruong3289** [comment]
@marcreichel 
I used version ^1.1.3

**Comment by marcreichel** [comment]
@vantruong3289 Could you please create a small project that reproduces the error and post a link here?

**Comment by vantruong3289** [comment]
@marcreichel  When i use wire.model not bug but i use wire.model.defer bug occur

**Comment by marcreichel** [comment]
@vantruong3289 Thanks for clarifying. I've fixed it with [`v1.1.4`](https://github.com/marcreichel/alpine-autosize/releases/tag/1.1.4).
