### ISSUE TITLE
Not correct sized after load with Phoenix LiveView

### ISSUE THREAD

**Issue by bitboxer** [marcreichel/alpine-autosize#13]
I tried to use this in an elixir phoenix app, but somehow the textarea is not resized on load, only after I changed something inside the textarea. Will try to debug why next week but wanted to already open the issue here.

**Comment by marcreichel** [comment]
@bitboxer This might relate to how the Phoenix app hydrates the data of the textarea I think.
I've not worked with the Phoenix framework yet though.

This package provides a `$autosize` Alpine magic, which can be used to trigger resizing of a textarea manually.

So maybe the Phoenix framework dispatches some sort of event or has a lifecycle hook you can use to trigger the resizing when the data got hydrated?

Something like this (pseudo code):

```html
<textarea x-autosize @phoenix:hydrated="$autosize()"></textarea>
```

Or if you do not have access to the Alpine scope, you can just dispatch the `autosize` Event on the textarea:

```html
<textarea x-autosize id="my-textarea"></textarea>
```

```javascript
document.getElementById("my-textarea").dispatchEvent(new Event("autosize"));
```

Hopefully this helps 🙂

**Comment by bitboxer** [comment]
Yes, that was the problem.

The solution is sadly a bit more complex because there is no direct way of getting those events:

Step 1: Add a new hook that fires the custom event and the listener to that event to your `textarea`

```html
<textarea
   ...
   x-autosize
   phx-hook="ElementMountedEvent"
   x-on:element-mounted="$autosize()"
></textarea>
```

Step 2: Add this hook to your `LiveSocket` initializer:

```javascript
ElementMountedEvent: {
  mounted() {
    const event = new CustomEvent("element-mounted", {});
    this.el.dispatchEvent(event);
  },
},
```

Now it is working perfectly.

**Comment by marcreichel** [comment]
@bitboxer Glad to hear it's working now 👌🏼
