### ISSUE TITLE
The CDN link in the docs is broken

### ISSUE THREAD

**Issue by calebporzio** [marcreichel/alpine-autosize#2]
Nice package! I tried to use it, but couldn't get past the broken CDN link: "https://cdn.jsdelivr.net/npm/@marcreichel/alpine-autosize@latest/dist/alpine-autosize.js"

**Comment by marcreichel** [comment]
@calebporzio Thanks man! And thanks for reporting this. I've fixed it and released v1.0.1 👍🏼
