### ISSUE TITLE
Doesn't respect textarea rows attribute

### ISSUE THREAD

**Issue by iniznet** [marcreichel/alpine-autosize#4]
It seems not able to respect the existing `rows` value on initial due to line 8 already setting the height,
https://github.com/marcreichel/alpine-autosize/blob/4abd4506cb42dc64eef2de3dd04700768872c396/src/index.js#L8-L9

Screenshot:
![image](https://user-images.githubusercontent.com/34362833/158486335-106a6b0a-8db2-483c-aae7-0da339a7ced0.png)

**Comment by marcreichel** [comment]
@iniznet Thanks for reporting. A fix is on its way 🙂

**Comment by marcreichel** [comment]
This behavior is now fixed in [v1.1.1](https://github.com/marcreichel/alpine-autosize/releases/tag/1.1.1). Feel free to update 🙂 @iniznet Thanks again for reporting this issue.
