### ISSUE TITLE
Textarea height is not enough to hide vertical scroll

### ISSUE THREAD

**Issue by antonkomarev** [marcreichel/alpine-autosize#9]
By default textarea has a scroll, but if its height will be larger on 2px we wouldn't have that issue. Otherwise we need to add `overflow-y: hidden;` CSS property. Tested in on Mac.

I've tried to add +2px to textarea height and scroll is disappearing.

https://user-images.githubusercontent.com/1849174/189544855-4daf64fa-0966-4f27-9de4-06eacebb16b2.mov

**Comment by marcreichel** [comment]
Hi @antonkomarev,

thanks for reporting this. I have not had this issue before though.
May I ask which browser you are using?

**Comment by antonkomarev** [comment]
Firefox

**Comment by marcreichel** [comment]
Thanks,
I do not have access to my computer atm.
I will look into this by end of the week 👍

**Comment by marcreichel** [comment]
@antonkomarev I could not reproduce your scroll issue. So maybe some styling of your textarea is causing this behavior.

I've just released [v1.2.0](https://github.com/marcreichel/alpine-autosize/releases/tag/1.2.0) of this package which introduces a new modifier. The modifier hopefully helps you to get rid of your scroll issue.

You can use it like this:

```html
<textarea x-data x-autosize.2px></textarea>
```

Here's the full documentation: https://github.com/marcreichel/alpine-autosize#-additional-height

Let me know if this fixes your issue.
